### ISSUE TITLE
Error:  'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by lennartvandeguchte** [ParallelMeaningBank/ComSem#1]
I'm getting the following error when trying to compare my tok.off files:

```
Traceback (most recent call last):
  File ".\tok_off_compare.py", line 187, in <module>
    matrix = compare_tok_off(raw_path, off_path, myoff_path, n=args.beam, verbose=args.verbose)
  File ".\tok_off_compare.py", line 135, in compare_tok_off
    (tois2, line_raw) = off2TOIS(raw, file2, verbose=verbose)
  File ".\tok_off_compare.py", line 55, in off2TOIS
    off_toks = [ re.match('(\d+) (\d+) (\d+)(\d{3}) (.+)\n$', line).groups() for line in off_file ]
AttributeError: 'NoneType' object has no attribute 'groups'
```

It seems like the tok.off file is not read in properly, which happens here (code lines 47-52) : 

```
    raw_file = codecs.open(raw_path, 'r', "utf-8")
    off_file = codecs.open(off_path, 'r', "utf-8") 
    raw = raw_file.read()
    raw_file.close()
    raw = raw.rstrip()
```

The off_file is only opened and not read but when I do read it it still doesn't work. Any idea how to solve this?

**Comment by kovvalsky** [comment]
Could you attach your en.tok.off file that causes this issue?

**Comment by kovvalsky** [comment]
off_file is read in the line:
`off_toks = [ re.match('(\d+) (\d+) (\d+)(\d{3}) (.+)\n$', line).groups() for line in off_file ]`
It seems line formatting issue.

**Comment by lennartvandeguchte** [comment]
Git does not support .off files so I can't attach them but for example I want to compare these files:

en.tok.off:
```
0 1 1001 “
1 2 1002 ‘
2 5 1003 But
5 6 1004 ,
6 7 1005 ’
8 12 1006 said
13 14 1007 I
14 15 1008 ,
16 22 1009 ‘there
23 28 1010 would
29 31 1011 be
32 40 1012 millions
41 43 1013 of
44 54 1014 red-headed
55 58 1015 men
59 62 1016 who
63 68 1017 would
69 74 1018 apply
74 75 1019 .
75 76 1020 ’
```
and en.tok.off.s2408287: 

```
0	1	1000	“	JJ
1	2	1001	‘	NN
2	5	1002	But	CC
5	6	1003	,	,
6	7	1004	’	NNP
8	12	1005	said	VBD
13	14	1006	I	PRP
14	15	1007	,	,
16	17	1008	‘	''
17	22	1009	there	EX
23	28	1010	would	MD
29	31	1011	be	VB
32	40	1012	millions	NNS
41	43	1013	of	IN
44	54	1014	red-headed	JJ
55	58	1015	men	NNS
59	62	1016	who	WP
63	68	1017	would	MD
69	74	1018	apply	VB
74	75	1019	.	.
75	76	1020	’	VB

```

**Comment by kovvalsky** [comment]
The script expects that original and your tok.off files have the same format and the lines shoudl match the regex `(\d+) (\d+) (\d+)(\d{3}) (.+)\n$`. In your case, your tok.off file has different formatting, tabs and POS-tags inside.

**Comment by lennartvandeguchte** [comment]
Ah, thanks! I thought the regex would ignore that.
